import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export default defineSchema({
  // Chat sessions - stores metadata about each conversation
  chatSessions: defineTable({
    sessionId: v.string(), // UUID generated by server
    userId: v.string(), // Clerk userId for auth users, generated UUID for anonymous
    title: v.string(), // First message snippet or custom title
    createdAt: v.number(), // Timestamp
    updatedAt: v.number(), // Last activity timestamp
  })
    .index('by_session_id', ['sessionId'])
    .index('by_user_id', ['userId'])
    .index('by_user_and_time', ['userId', 'updatedAt']),

  // Chat messages - stores individual messages in a session
  chatMessages: defineTable({
    sessionId: v.string(), // Reference to chat session
    messageId: v.string(), // Client-generated unique ID for deduplication
    role: v.union(v.literal('user'), v.literal('assistant')),
    content: v.string(), // Message text content
    createdAt: v.number(), // Timestamp
  })
    .index('by_session_id', ['sessionId'])
    .index('by_session_and_time', ['sessionId', 'createdAt'])
    .index('by_message_id', ['messageId']),

  // Rate limiting - tracks daily message counts
  rateLimits: defineTable({
    identifier: v.string(), // userId for auth users, IP address for anonymous
    identifierType: v.union(v.literal('user'), v.literal('ip')),
    date: v.string(), // YYYY-MM-DD format for daily tracking
    messageCount: v.number(), // Number of messages sent today
    updatedAt: v.number(), // Last update timestamp
  })
    .index('by_identifier_and_date', ['identifier', 'date'])
    .index('by_date', ['date']), // For cleanup of old records
})
