import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export default defineSchema({
  // Chat sessions - stores metadata about each conversation
  chatSessions: defineTable({
    sessionId: v.string(), // UUID generated by server
    userId: v.string(), // Clerk userId for auth users, generated UUID for anonymous
    title: v.string(), // First message snippet or custom title
    createdAt: v.number(), // Timestamp
    updatedAt: v.number(), // Last activity timestamp
  })
    .index('by_session_id', ['sessionId'])
    .index('by_user_id', ['userId'])
    .index('by_user_and_time', ['userId', 'updatedAt']),

  // Chat messages - stores individual messages in a session
  chatMessages: defineTable({
    sessionId: v.string(), // Reference to chat session
    messageId: v.string(), // Client-generated unique ID for deduplication
    role: v.union(v.literal('user'), v.literal('assistant')),
    content: v.string(), // Message text content
    createdAt: v.number(), // Timestamp
  })
    .index('by_session_id', ['sessionId'])
    .index('by_session_and_time', ['sessionId', 'createdAt'])
    .index('by_message_id', ['messageId']),
})
